# Generated by Django 2.2.1 on 2019-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=200)),
                ('Marca', models.CharField(max_length=200)),
                ('Transmision', models.CharField(max_length=200)),
                ('Tipo', models.CharField(max_length=200)),
                ('Puertas', models.FloatField()),
            ],
        ),
    ]
